Настраивает логику получения данных по предложению
htmlacademy-react/1489861-six-cities-7 pull request #12
Opened 2021-07-14 12:44 UTC by El-Leto

2021-07-16 21:17 UTC, El-Leto commented
Не удалось очистить форму для отправки комментария. Если проверить state для отзыва, то он сбрасывается до пустого, но не смогла реализоваться. чтобы сбросилась форма.

2021-07-17 17:50 UTC, dtsaryov commented
@El-Leto 

> Не удалось очистить форму для отправки комментария. Если проверить state для отзыва, то он сбрасывается до пустого, но не смогла реализовать, чтобы сбросилась форма.

Нужно явно привязать все input'ы к state, тогда все заработает

2021-07-17 17:52 UTC, dtsaryov reviewed
Еще обрати внимание, что ругается на проблему с Link to в header-auth

2021-07-17 17:52 UTC, dtsaryov commented on project/src/components/room-page/room-page.jsx
> +  hotel,
Постоянно возникает ошибка, что hotel.bedrooms undefined - обрати внимание

2021-07-17 17:53 UTC, dtsaryov requested changes

2021-07-17 17:53 UTC, dtsaryov commented on project/src/components/review-form/review-form.jsx
> +function ReviewsForm({ id, sendReview }) {
Еще нет проверки на 50 символов

2021-07-18 11:51 UTC, dtsaryov commented on project/src/components/app/hotel.prop.js
> -  bedrooms: PropTypes.number.isRequired,
А зачем мы все isRequired поснимали?

2021-07-18 11:51 UTC, dtsaryov commented on project/src/components/review-form/review-form.jsx
> +    onSendSuccess();
А зачем так сложно?

2021-07-18 11:51 UTC, dtsaryov commented on project/src/components/review-form/review-form.jsx
> +        <input className="form__rating-input visually-hidden" name="rating" value="5" id="5-stars" type="radio" onClick={(evt) => {setReview({...review, rating: Number(evt.target.value)});}} />
Всё еще не вижу привязки к состоянию

для рейтинга через checked, для коммента через value

2021-07-18 11:51 UTC, merged

2021-07-18 11:59 UTC, El-Leto commented on project/src/components/app/hotel.prop.js
> -  bedrooms: PropTypes.number.isRequired,
потому что ругался в консоли на undefined