Module5 task2
htmlacademy-react/1489861-six-cities-7 pull request #9
Opened 2021-07-01 20:32 UTC by El-Leto

Привет, у меня парочка вопросов.
Когда заходишь на страницу предложения и обновляешь ее, то страница не загружается и появляется куча ошибок. Не совсем понимаю, как это можно исправить.
И еще в консоли ошибка "Warning: Failed prop type: Invalid prop `activeCard` of type `string` supplied to `MapPage`, expected `object`." В файле map-page.jsx  написала вот так: activeCard: PropTypes.object.isRequired,. Но консоль продолжает ругаться.

2021-07-03 12:13 UTC, dtsaryov commented
При наведении на карточку в списке

<img width="798" alt="Screen Shot 2021-07-03 at 3 12 47 PM" src="https://user-images.githubusercontent.com/6183810/124353772-25b36280-dc11-11eb-83a9-6cc24e668452.png">

2021-07-03 12:24 UTC, dtsaryov commented
> И еще в консоли ошибка "Warning: Failed prop type: Invalid prop activeCard of type string supplied to MapPage, expected object." В файле map-page.jsx написала вот так: activeCard: PropTypes.object.isRequired,. Но консоль продолжает ругаться.

1. activeCard может и не быть, если пользователь не навел мышкой ни на одну карточку, а это значит, что `isRequired` использовать некорректно
2. Не надо "смешивать" типы данных:
```JSX
<PlaceList
  isMainPage
  hotels={sortedHotels}
  onMouseEnter={onCardHover}
  onMouseLeave={() => setActiveCard(null)} // вот здесь у тебя была пустая строка
/>
```
3. в `map-page.jsx`: `(activeCard && id === activeCard.id)`

2021-07-03 12:25 UTC, dtsaryov commented
> Когда заходишь на страницу предложения и обновляешь ее, то страница не загружается и появляется куча ошибок. Не совсем понимаю, как это можно исправить.

Это не смог воспроизвести

2021-07-03 12:29 UTC, dtsaryov requested changes

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/main-page/main-page.jsx
> +                onMouseLeave={() => setActiveCard('')}
setActiveCard(null)

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/map-page/map-page.jsx
> +                (id === activeCard.id)
activeCard может не быть

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/map-page/map-page.jsx
> +  activeCard: PropTypes.object.isRequired,
activeCard может не быть

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/site-sort/site-sort.jsx
> +function SiteSort({ sorts, activeSort }) {
Ну точно не SiteSort - мы всего лишь сортируем предложения

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/site-sort/site-sort.jsx
> +  sorts: PropTypes.arrayOf(PropTypes.string.isRequired).isRequired,
sortTypes

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/site-sort/site-sort.jsx
> +  changeSort: ActionCreator.changeSort,
setSortType

2021-07-03 12:29 UTC, dtsaryov commented on project/src/components/site-sort-item/site-sort-item.jsx
> +function SiteSortItem({ item, changeSort, activeSort }) {
Все комменты аналогично модулю `site-sort`

2021-07-06 13:59 UTC, El-Leto commented
> > Когда заходишь на страницу предложения и обновляешь ее, то страница не загружается и появляется куча ошибок. Не совсем понимаю, как это можно исправить.
> 
> Это не смог воспроизвести

Да, я неверно тут написала. При обновлении страницы обновляется верно. А если зайти на страницу предложения, а потом вручную исправить адрес, например с http://localhost:3000/offer/4 на http://localhost:3000/offer/3, вот тогда выдает ошибки.

2021-07-06 17:56 UTC, dtsaryov commented
> Да, я неверно тут написала. При обновлении страницы обновляется верно. А если зайти на страницу предложения, а потом вручную исправить адрес, например с http://localhost:3000/offer/4 на http://localhost:3000/offer/3, вот тогда выдает ошибки.

Это нормально, мы реализуем это позднее

2021-07-06 17:56 UTC, dtsaryov approved these changes

2021-07-06 17:57 UTC, merged